# variables = 5
# observations = 100
# samples = 10
# bootstrap = 10
# layers = [4, 3, 2]

# variables = 5
# observations = 10000
# samples = 100
# bootstrap = 1000
# layers = [10,9,8,7,6,5,4,3,2,1]


variables = 50
observations = 5000
samples = 100
bootstrap = 1000
layers = [500,500,300]
